# Generated by Django 4.2.2 on 2023-06-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_auto_20210607_1331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
