# Generated by Django 3.1.7 on 2021-05-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover_pic',
            field=models.ImageField(upload_to='cpics'),
        ),
    ]
