# Generated by Django 3.1.7 on 2021-07-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210705_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='video',
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(),
        ),
    ]
